### ISSUE TITLE
asertionerror and typeerror

### ISSUE THREAD

**Issue by ghost** [henrysher/duplicity#25]
can't be arsed to make a proper bug report at the proper place so ima just dump it here.

```
Traceback (most recent call last):
  File "/usr/bin/duplicity", line 106, in <module>
    with_tempdir(main)
  File "/usr/bin/duplicity", line 92, in with_tempdir
    fn()
  File "/usr/lib/python3/dist-packages/duplicity/dup_main.py", line 1538, in main
    do_backup(action)
  File "/usr/lib/python3/dist-packages/duplicity/dup_main.py", line 1618, in do_backup
    restore(col_stats)
  File "/usr/lib/python3/dist-packages/duplicity/dup_main.py", line 723, in restore
    if not patchdir.Write_ROPaths(globals.local_path,
  File "/usr/lib/python3/dist-packages/duplicity/patchdir.py", line 580, in Write_ROPaths
    ITR(ropath.index, ropath)
  File "/usr/lib/python3/dist-packages/duplicity/lazy.py", line 365, in __call__
    self.process_w_branch(index, branch, args)
  File "/usr/lib/python3/dist-packages/duplicity/lazy.py", line 319, in process_w_branch
    robust.check_common_error(branch.on_error,
  File "/usr/lib/python3/dist-packages/duplicity/robust.py", line 41, in check_common_error
    return function(*args)
  File "/usr/lib/python3/dist-packages/duplicity/patchdir.py", line 613, in start_process
    assert index == (), index
AssertionError: (b'home', b'autoplayer', b'Desktop', b'server minecraft', b'bedwars', b'plugins', b'updater')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/duplicity", line 162, in <module>
    if u"Forced assertion for testing" in util.uexc(e):
TypeError: argument of type 'NoneType' is not iterable
```

was restoring a duplicity backup on an exfat drive, from and to that drive, in ubuntu wsl. backup is of an ubuntu rootfs

**Comment by BenWoodworth** [comment]
I have a similar error. Looking in the backup folder, some of the volumes from the first full backup are missing.

Kind of annoying, since the following incremental updates (by Deja Dup) were created without any signs of the backup being broken, and now I can't restore.

<details>
<summary>Traceback</summary>
Traceback (most recent call last):
  File "/usr/bin/duplicity", line 162, in <module>
    if u"Forced assertion for testing" in util.uexc(e):
TypeError: argument of type 'NoneType' is not iterable
Restoring: home/ben/IdeaProjects/FastCraft/.git/objects/cf/0252ad6ed7991adbd920c3b8fad64101f8ccde
Traceback (most recent call last):
  File "/usr/bin/duplicity", line 106, in <module>
    with_tempdir(main)
  File "/usr/bin/duplicity", line 92, in with_tempdir
    fn()
  File "/usr/lib/python3/dist-packages/duplicity/dup_main.py", line 1538, in main
    do_backup(action)
  File "/usr/lib/python3/dist-packages/duplicity/dup_main.py", line 1618, in do_backup
    restore(col_stats)
  File "/usr/lib/python3/dist-packages/duplicity/dup_main.py", line 723, in restore
    if not patchdir.Write_ROPaths(globals.local_path,
  File "/usr/lib/python3/dist-packages/duplicity/patchdir.py", line 578, in Write_ROPaths
    for ropath in rop_iter:
  File "/usr/lib/python3/dist-packages/duplicity/patchdir.py", line 541, in integrate_patch_iters
    for patch_seq in collated:
  File "/usr/lib/python3/dist-packages/duplicity/patchdir.py", line 407, in yield_tuples
    setrorps(overflow, elems)
  File "/usr/lib/python3/dist-packages/duplicity/patchdir.py", line 396, in setrorps
    elems[i] = next(iter_list[i])
  File "/usr/lib/python3/dist-packages/duplicity/patchdir.py", line 111, in filter_path_iter
    for path in path_iter:
  File "/usr/lib/python3/dist-packages/duplicity/patchdir.py", line 126, in difftar2path_iter
    tarinfo_list = [next(tar_iter)]
  File "/usr/lib/python3/dist-packages/duplicity/patchdir.py", line 355, in __next__
    self.set_tarfile()
  File "/usr/lib/python3/dist-packages/duplicity/patchdir.py", line 348, in set_tarfile
    self.current_fp = next(self.fileobj_iter)
  File "/usr/lib/python3/dist-packages/duplicity/dup_main.py", line 760, in get_fileobj_iter
    backup_set.volume_name_dict[vol_num],
KeyError: 257

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/duplicity", line 162, in <module>
    if u"Forced assertion for testing" in util.uexc(e):
TypeError: argument of type 'NoneType' is not iterable
</details>
